import { inter, nunito, quicksand, mulish } from '@/app/ui/fonts';
import './globals.css';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={`${mulish.className} antialiased`}>{children}</body>
		</html>
	);
}
